# Generated by Django 5.1.7 on 2025-04-26 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HypertensionPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('heart_disease', models.CharField(max_length=5)),
                ('smoking_history', models.CharField(max_length=20)),
                ('bmi', models.FloatField()),
                ('HbA1c_level', models.FloatField()),
                ('blood_glucose_level', models.FloatField()),
                ('diabetes', models.CharField(max_length=5)),
                ('prediction', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
