# Generated by Django 5.1.7 on 2025-04-25 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiabetesPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('hypertension', models.CharField(max_length=5)),
                ('heart_disease', models.CharField(max_length=5)),
                ('smoking_history', models.CharField(max_length=20)),
                ('bmi', models.FloatField()),
                ('HbA1c_level', models.FloatField()),
                ('blood_glucose_level', models.FloatField()),
                ('prediction', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
