# Generated by Django 5.1.7 on 2025-04-20 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0005_user_usergender_user_userheight_user_userweight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_start', models.DateTimeField()),
                ('sleep_end', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to='userManagement.user')),
            ],
        ),
    ]
