# Generated by Django 5.1.5 on 2025-01-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('UserFirstName', models.CharField(max_length=200)),
                ('UserLastName', models.CharField(max_length=200)),
                ('UserEmail', models.EmailField(max_length=200)),
                ('UserPassword', models.CharField(max_length=200)),
            ],
        ),
    ]
