# Generated by Django 5.1.5 on 2025-01-26 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserGender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='UserHeight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='UserWeight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='UserEmail',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
