# Generated by Django 5.1.7 on 2025-04-28 21:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
                ('serving_size', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbohydrates_total_g', models.FloatField()),
                ('fat_saturated', models.FloatField()),
                ('fat_total_g', models.FloatField()),
                ('sugar_g', models.FloatField()),
                ('fiber_g', models.FloatField()),
                ('potassium_mg', models.FloatField()),
                ('sodium_g', models.FloatField()),
                ('cholesterol_mg', models.FloatField()),
                ('meal_log_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_log',
                'ordering': ['-meal_log_time'],
            },
        ),
    ]
