# Generated by Django 5.1.7 on 2025-04-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurition_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlog',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Breakfast', max_length=10),
        ),
    ]
